### ISSUE TITLE
Not fully understanding

### ISSUE THREAD

**Issue by cb12438** [win32kbase/MuckInternal#2]
what do you mean by

Select game and DLL file

Thier is multibole .DLL files for the game what specific .dll file

**Comment by cb12438** [comment]
Also is thier a discord for this

**Comment by blakkkk** [comment]
I believe Assembly-CSharp.dll is the main file so try that. Should be the first one.

**Comment by blakkkk** [comment]
Nevermind. I believe the DLL file you have to select is the one that you have built using Visual Studio.

**Comment by cb12438** [comment]
Alright yep that worked how do i open the GUI in game now

**Comment by cb12438** [comment]
ok i got the gui to open mut item spawning works just cant pick it up

**Comment by cb12438** [comment]
And you cant spawn in the sneakers power up as its not thier in the menu

**Comment by cb12438** [comment]
hes also missing the health and sheuld pills

**Comment by win32kbase** [comment]
Power ups are at the bottom of the item spawner

**Comment by cb12438** [comment]
yep i see that but your missing a few and i still cant pick up items

**Comment by win32kbase** [comment]
The items are grabbed dynamically from the game, if something is missing then that is confusing

**Comment by cb12438** [comment]
Ill retry it maybe i had a error of some sort

**Comment by cb12438** [comment]
![Screenshot (311)](https://user-images.githubusercontent.com/55159369/122095378-2a2eed00-cdc2-11eb-8fd6-6ec4a2dd87dc.png)

**Comment by cb12438** [comment]
yea still not thier i cant pick up item either

**Comment by cb12438** [comment]
Bassicly i can get the power ups just not the items should i try reinstalling the mod?

**Comment by andreaund3r** [comment]
I have the same problem. I see the menu just like you do. Waiting with you!

**Comment by win32kbase** [comment]
Spawning works fine for me when I am the host. If you are not the host of the lobby I am unsure if it will work.

**Comment by cb12438** [comment]
yes spawning works fine its the licking up the items
