### ISSUE TITLE
Create BepInEx mod from source

### ISSUE THREAD

**Issue by blakkkk** [win32kbase/MuckInternal#3]
Instead of injecting you could create a BepInEx mod so you don't have to directly edit the game files. I would if I could but I'm not really sure what method/class (I'm not great with C#) to patch.

**Comment by win32kbase** [comment]
I have no idea what BepInEx is

**Comment by win32kbase** [comment]
If you find a good class feel free to open a PR

**Comment by blakkkk** [comment]
BepInEx is a modloader for Unity games. You just have to say what method and class you want to patch. I don't really understand C# that well and don't really know what I'm doing so I'm not sure I can do it.  [BepInEx](https://github.com/BepInEx/BepInEx)
