### ISSUE TITLE
Spawning items

### ISSUE THREAD

**Issue by cb12438** [win32kbase/MuckInternal#4]
Spawning works fine for me when I am the host. If you are not the host of the lobby I am unsure if it will work.

_Originally posted by @win32kbase in https://github.com/win32kbase/MuckInternal/issues/2#issuecomment-861772933_

Spawning works fine we just cant pickup the items i am the host of the lobby as well

**Comment by cb12438** [comment]
Even when im not the host still cant pick up items

**Comment by win32kbase** [comment]
Can't reproduce. Works fine for me.

**Comment by win32kbase** [comment]
nvm, found the problem

**Comment by win32kbase** [comment]
Compile and use https://github.com/win32kbase/MuckInternal/commit/ac196586c1e5034e2292f8474dee4910b476e619 should work now
