### ISSUE TITLE
Missing items in the spawning menu

### ISSUE THREAD

**Issue by andreaund3r** [win32kbase/MuckInternal#5]
Spawning works fine, even if im not the host of the lobby.
The thing is that there are missing artefacts. Should i reinstall it?

**Comment by win32kbase** [comment]
artefacts?

**Comment by andreaund3r** [comment]
The powerups, the upgrades, like the blue pill or the red one, or the orange juice. They're all missing from the menu.

**Comment by win32kbase** [comment]
Orange juice shows up in the menu for me. Though, the blue and red pills are missing. Seems they're not populated in the allPowerups array for whatever reason. Looking at it

**Comment by win32kbase** [comment]
Yeah for some reason they're just not in that array. Not sure how to fix that. I'm assuming it's an issue with the game.
