### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by XRogZ** [win32kbase/MuckInternal#8]
i need help it keeps saying Injection failed
![image](https://user-images.githubusercontent.com/86732013/123987020-1f31aa80-d9c7-11eb-8551-d08903aafdb7.png)
![image](https://user-images.githubusercontent.com/86732013/123987113-36709800-d9c7-11eb-9098-6471702679ea.png)

**Comment by win32kbase** [comment]
Version on UC is outdated and I am banned so I can't update it. You'll just have to compile it yourself with the updated assemblies
